#' constants
#'
#' @file constants.R
#' @author Mariko Ohtsuka
#' @date 2024.1.31
# ------ constants ------
# https://webofscience.help.clarivate.com/ja-jp/Content/wos-core-collection/wos-core-collection.htm
# https://images.webofknowledge.com/WOKRS59B4/help/ja/WOS/hp_research_areas_easca.html
kDfSubHeading <- data_list <- list(
  c("Acoustics", "音響学"),
  c("Electrochemistry", "電気化学"),
  c("Literature", "文学"),
  c("Physics, Condensed Matter", "物理学、凝縮物質"),
  c("Agricultural Economics & Policy", "農業経済学、農業政策"),
  c("Emergency Medicine", "救急医学"),
  c("Literature, African, Australian, Canadian", "文学、アフリカ、オーストラリア、カナダ"),
  c("Physics, Fluids & Plasmas", "物理学、流体、プラズマ"),
  c("Agricultural Engineering", "農業工学"),
  c("Endocrinology & Metabolism", "内分泌学、新陳代謝"),
  c("Literature, American", "文学、アメリカ"),
  c("Physics, Mathematical", "物理学、数理"),
  c("Agriculture, Dairy & Animal Science", "農学、酪農学、畜産学"),
  c("Energy & Fuels", "エネルギー、燃料"),
  c("Literature, British Isles", "文学、イギリス"),
  c("Physics, Multidisciplinary", "物理学、総合"),
  c("Agriculture, Multidisciplinary", "農学、総合"),
  c("Engineering, Aerospace", "工学、航空宇宙"),
  c("Literature, German, Dutch, Scandinavian", "文学、ドイツ、オランダ、北欧"),
  c("Physics, Nuclear", "物理学、核"),
  c("Agronomy", "作物栽培学"),
  c("Engineering, Biomedical", "工学、生医学"),
  c("Literature, Romance", "文学、ロマンス"),
  c("Physics, Particles & Fields", "物理学、粒子、界"),
  c("Allergy", "アレルギー"),
  c("Engineering, Chemical", "工学、化学"),
  c("Literature, Slavic", "文学、スラブ"),
  c("Physiology", "生理学"),
  c("Anatomy & Morphology", "解剖学、形態学"),
  c("Engineering, Civil", "工学、土木"),
  c("Logic", "論理学"),
  c("Planning & Development", "企画開発"),
  c("Andrology", "男性病学"),
  c("Engineering, Electrical & Electronic", "工学、電気電子"),
  c("Management", "経営学"),
  c("Plant Sciences", "植物学"),
  c("Anesthesiology", "麻酔学"),
  c("Engineering, Environmental", "工学、環境"),
  c("Marine & Freshwater Biology", "海洋生物学、淡水生物学"),
  c("Poetry", "詩学"),
  c("Anthropology", "人類学"),
  c("Engineering, Geological", "工学、地質"),
  c("Materials Science, Biomaterials", "物質科学、生体材料"),
  c("Political Science", "政治学"),
  c("Archaeology", "考古学"),
  c("Engineering, Industrial", "工学、産業"),
  c("Materials Science, Ceramics", "物質科学、セラミックス"),
  c("Polymer Science", "高分子科学"),
  c("Architecture", "建築"),
  c("Engineering, Manufacturing", "工学、製造"),
  c("Primary Health Care", "プライマリヘルスケア"),
  c("Area Studies", "地域研究"),
  c("Engineering, Marine", "工学、船舶"),
  c("Materials Science, Coatings & Films", "物質科学、塗料、塗膜"),
  c("Psychiatry", "精神医学"),
  c("Engineering, Mechanical", "工学、機械"),
  c("Materials Science, Composites", "物質科学、複合材料"),
  c("Psychology", "心理学"),
  c("Engineering, Multidisciplinary", "工学、総合"),
  c("Materials Science, Crystallography", "物質科学、結晶学"),
  c("Automation & Control Systems", "オートメーション、制御システム"),
  c("Engineering, Petroleum", "工学、石油"),
  c("Materials Science, Multidisciplinary", "物質科学、総合"),
  c("Behavioral Sciences", "行動科学"),
  c("Engineering, Petroleum, Gas & Fuels", "工学、石油、ガス、燃料"),
  c("Gastroenterology & Hepatology", "消化器病学、肝臓病学"),
  c("Mathematical & Computational Biology", "数理、計算生物学"),
  c("Physics, Acoustics", "物理学、音響学"),
  c("Physics, Applied", "物理学、応用"),
  c("Gender Studies", "ジェンダー研究"),
  c("Mathematics", "数学"),
  c("Physics, Atomic, Molecular & Chemical", "物理学、原子分子化学"),
  c("Genetics & Heredity", "遺伝学、遺伝"),
  c("Medicine, General & Internal", "医学、一般、内科"),
  c("Physics, Biophysics", "物理学、生物物理学"),
  c("Geography", "地理学"),
  c("Medicine, Legal", "医学、法医学"),
  c("Geology", "地質学"),
  c("Medicine, Research & Experimental", "医学、研究、実験"),
  c("Geriatrics & Gerontology", "老年医学、老年学"),
  c("Medicine, Rehabilitation", "医学、リハビリテーション"),
  c("Medicine, Respiratory System", "医学、呼吸器系"),
  c("Medicine, Sports Sciences", "医学、スポーツ科学"),
  c("History & Philosophy Of Science", "科学の歴史と哲学"),
  c("Medicine, Critical Care", "医学、集中治療"),
  c("Physics, Particle & Field", "物理学、粒子、場"),
  c("Horticulture", "園芸学"),
  c("Medicine, Emergency Medicine", "医学、救急医学"),
  c("Physics, Plasma", "物理学、プラズマ"),
  c("Hospitality, Leisure, Sport & Tourism", "ホスピタリティ、レジャー、スポーツ、観光"),
  c("Medicine, Experimental", "医学、実験"),
  c("Imaging Science & Photographic Technology", "画像科学、写真技術"),
  c("Immunology", "免疫学"),
  c("Industrial Relations & Labor", "産業関係、労働"),
  c("Infectious Diseases", "感染症"),
  c("Instruments & Instrumentation", "機器、計器"),
  c("Integrative & Complementary Medicine", "統合医療、補完代替医療"),
  c("International Relations", "国際関係"),
  c("Investigative Dermatology", "皮膚科学研究"),
  c("Law", "法学"),
  c("Materials Science, Characterization & Testing", "物質科学、特性試験"),
  c("Library Science", "図書館学"),
  c("Linguistics", "言語学"),
  c("Literary Theory & Criticism", "文学理論、評論"),
  c("Materials Science, Paper & Wood", "物質科学、紙、木材"),
  c("Marketing", "マーケティング"),
  c("Materials Science, Nanoscience & Nanotechnology", "物質科学、ナノ科学、ナノテクノロジー"),
  c("Mathematics, Applied", "数学、応用"),
  c("Mathematics, Interdisciplinary Applications", "数学、異分野応用"),
  c("Mathematics, Mathematical Logic", "数学、数理論理学"),
  c("Materials Science, Textiles", "物質科学、テキスタイル"),
  c("Mechanics", "力学"),
  c("Medical Ethics", "医療倫理"),
  c("Medical Informatics", "医療情報学"),
  c("Medical Laboratory Technology", "医療技術研究"),
  c("Metallurgy & Metallurgical Engineering", "冶金学、冶金工学"),
  c("Meteorology & Atmospheric Sciences", "気象学、大気科学"),
  c("Microbiology", "微生物学"),
  c("Mineralogy", "鉱物学"),
  c("Mining & Mineral Processing", "鉱業、鉱物処理"),
  c("Multidisciplinary Sciences", "総合科学"),
  c("Music", "音楽学"),
  c("Nanoscience & Nanotechnology", "ナノ科学、ナノテクノロジー"),
  c("Neuroimaging", "神経画像"),
  c("Neurosciences", "神経科学"),
  c("Nuclear Medicine", "核医学"),
  c("Nursing", "看護学"),
  c("Nutrition & Dietetics", "栄養学、食事療法"),
  c("Oceanography", "海洋学"),
  c("Oncology", "腫瘍学"),
  c("Operations Research", "オペレーションズリサーチ"),
  c("Ophthalmology", "眼科学"),
  c("Optics", "光学"),
  c("Orthopedics", "整形外科学"),
  c("Otorhinolaryngology", "耳鼻咽喉科学"),
  c("Paleontology", "古生物学"),
  c("Parasitology", "寄生虫学"),
  c("Pathology", "病理学"),
  c("Pediatrics", "小児科学"),
  c("Pharmacology & Pharmacy", "薬理学、薬学"),
  c("Philosophy", "哲学"),
  c("Radiology, Nuclear Medicine & Medical Imaging", "放射線学、核医学、医学画像学"),
  c("Rehabilitation", "リハビリテーション"),
  c("Remote Sensing", "リモートセンシング"),
  c("Reproductive Biology", "生殖生物学"),
  c("Respiratory System", "呼吸器系"),
  c("Rheumatology", "リウマチ学"),
  c("Social Sciences, Biomedical", "社会科学、生体医学"),
  c("Social Sciences, Interdisciplinary", "社会科学、異分野研究"),
  c("Social Work", "社会福祉"),
  c("Sociology", "社会学"),
  c("Soil Science", "土壌科学"),
  c("Sport Sciences", "スポーツ科学"),
  c("Statistics & Probability", "統計学、確率"),
  c("Substance Abuse", "物質乱用"),
  c("Surgery", "外科学"),
  c("Thermodynamics", "熱力学"),
  c("Toxicology", "毒性学"),
  c("Transplantation", "移植"),
  c("Tropical Medicine", "熱帯医学"),
  c("Urban Studies", "都市研究"),
  c("Urology & Nephrology", "泌尿器科学、腎臓学"),
  c("Veterinary Sciences", "獣医学"),
  c("Virology", "ウイルス学"),
  c("Women's Studies", "女性研究"),
  c("Zoology", "動物学"),
  c("Agriculture", "農学"),
  c("Art", "芸術"),
  c("Arts & Humanities", "芸術、人文 - その他のトピック"),
  c("Asian Studies", "アジア研究"),
  c("Astronomy & Astrophysics", "天文学、宇宙物理学"),
  c("Audiology & Speech-Language Pathology", "聴覚学、音声言語病理学"),
  c("Biochemistry & Molecular Biology", "生化学、分子生物学"),
  c("Biodiversity & Conservation", "生物多様性保全"),
  c("Biomedical Social Sciences", "生医学社会科学"),
  c("Biophysics", "生物物理学"),
  c("Biotechnology & Applied Microbiology", "バイオテクノロジ、応用微生物学"),
  c("Business & Economics", "ビジネス、経済学"),
  c("Cardiovascular System & Cardiology", "循環器系、心臓学"),
  c("Cell Biology", "細胞生物学"),
  c("Chemistry", "化学"),
  c("Classics", "古典"),
  c("Communication", "通信"),
  c("Computer Science", "コンピューターサイエンス"),
  c("Construction & Building Technology", "土木技術、建築技術"),
  c("Criminology & Penology", "犯罪学、刑罰学"),
  c("Critical Care Medicine", "集中治療医学"),
  c("Crystallography", "結晶学"),
  c("Cultural Studies", "文化研究"),
  c("Dance", "ダンス"),
  c("Demography", "人口統計学"),
  c("Dentistry, Oral Surgery & Medicine", "歯科学、口腔外科、口腔内科"),
  c("Dermatology", "皮膚病学"),
  c("Development Studies", "開発学"),
  c("Developmental Biology", "発生生物学"),
  c("Education & Educational Research", "教育学、教育研究"),
  c("Engineering", "工学"),
  c("Entomology", "昆虫学"),
  c("Environmental Sciences & Ecology", "環境科学、生態学"),
  c("Ethnic Studies", "民族研究"),
  c("Evolutionary Biology", "進化生物学"),
  c("Family Studies", "家族研究"),
  c("Film, Radio & Television", "映画、ラジオ、テレビ"),
  c("Fisheries", "水産業"),
  c("Food Science & Technology", "食品科学、食品技術"),
  c("Forestry", "林学"),
  c("General & Internal Medicine", "一般医療、内科学"),
  c("Geochemistry & Geophysics", "地球化学、地球物理学"),
  c("Government & Law", "政府、法学"),
  c("Health Care Sciences & Services", "ヘルスケア科学、サービス"),
  c("Hematology", "血液学"),
  c("History & Philosophy of Science", "科学史、科学哲学"),
  c("History", "史学"),
  c("Information Science & Library Science", "情報科学、図書館学"),
  c("Legal Medicine", "法医学"),
  c("Life Sciences & Biomedicine", "生命科学、生体臨床医学 - その他のトピック"),
  c("Materials Science", "物質科学"),
  c("Mathematical Methods In Social Sciences", "社会科学の数学的手法"),
  c("Microscopy", "顕微鏡検査"),
  c("Mycology", "菌類学"),
  c("Neurosciences & Neurology", "神経科学、神経学"),
  c("Nuclear Science & Technology", "核科学、核技術"),
  c("Obstetrics & Gynecology", "産科学、婦人科学"),
  c("Operations Research & Management Science", "オペレーションズリサーチ、経営科学"),
  c("Physical Geography", "自然地理学"),
  c("Physics", "物理学"),
  c("Public Administration", "行政学"),
  c("Public, Environmental & Occupational Health", "公衆衛生学、環境衛生学、労働衛生学"),
  c("Religion", "宗教"),
  c("Research & Experimental Medicine", "研究、実験医学"),
  c("Robotics", "ロボット工学"),
  c("Science & Technology", "科学、技術 - その他のトピック"),
  c("Social Issues", "社会問題"),
  c("Social Sciences", "社会科学 - その他のトピック"),
  c("Spectroscopy", "分光学"),
  c("Telecommunications", "電気通信"),
  c("Theater", "演劇"),
  c("Transportation", "交通運輸"),
  c("Water Resources", "水資源"),
  c("Biology", "生物学"),
  c("Life Sciences & Biomedicine - Other Topics", "生命科学、生体臨床医学 - その他のトピック"),
  c("Peripheral Vascular Disease", "末梢血管疾患"),
  c("Clinical Neurology", "臨床神経学"),
  c("Cardiac & Cardiovascular Systems", "心臓、循環器系"),
  c("Gerontology", "老年学"),
  c("Health Policy & Services", "医療政策、サービス"),
  c("Cell & Tissue Engineering", "細胞、再生医学"),
  c("Science & Technology - Other Topics", "科学、技術 - その他のトピック"),
  c("Chemistry, Medicinal", "化学、医薬品"),
  c("Education, Scientific Disciplines", "教育学、科学分野"),
  c("Biochemical Research Methods", "生化学研究法"),
  c("Psychology, Multidisciplinary", "心理学、総合"),
  c("Chemistry, Analytical", "化学、分析"),
  c("Chemistry, Multidisciplinary", "化学、総合"),
  c("Humanities, Multidisciplinary", "人文学、総合"),
  c("Arts & Humanities - Other Topics", "芸術、人文 - その他のトピック"),
  c("Social Sciences - Other Topics", "社会科学 - その他のトピック"),
  c("Psychology, Clinical", "心理学、臨床"),
  c("Environmental Sciences", "環境科学"),
  c("Ethics", "論理学"),
  c("Psychology, Experimental", "心理学、実験"),
  c("Computer Science, Information Systems", "コンピューターサイエンス、情報システム"),
  c("Chemistry, Physical", "化学、物理"),
  c("Green & Sustainable Science & Technology", "環境、サステイナビリティ科学、技術"),
  c("Environmental Studies", "環境研究"),
  c("Computer Science, Artificial Intelligence", "コンピューターサイエンス、人工知能"),
  c("Geosciences, Multidisciplinary", "地球科学、総合"),
  c("Psychology, Biological", "心理学、生物")
) %>% unlist() %>% matrix(ncol = 2, byrow = T) %>% data.frame()
colnames(kDfSubHeading) <- c("subheading", "Translation")
kDfHeading <- list(
  c("Arts & Humanities", "芸術、人文"),
  c("Life Sciences & Biomedicine", "生命科学、生体臨床医学"),
  c("Physical Sciences", "物理科学"),
  c("Social Sciences", "社会科学"),
  c("Technology", "技術")
) %>% unlist() %>% matrix(ncol = 2, byrow = T) %>% data.frame()
colnames(kDfHeading) <- c("heading", "Translation")
# ------ functions ------
ConvertListToDf <- function(list_data, element_name1, element_name2) {
  list_data %>%
  map(~ tibble(uid = .x$uid, !!element_name2 := unlist(.x$category_info[[element_name1]][[element_name2]]))) %>%
  map_df(as.data.frame)
}
CombineContent <- function(subjects_list, ascatype_filter = "extended") {
  df_subject <- subjects_list %>%
    map_dfr(~ tibble(
      uid = .x$uid,
      ascatype = map_chr(.x$subject, "ascatype"),
      content = map_chr(.x$subject, "content")
    ))

  df_subject_combined <- df_subject %>%
    group_by(uid, ascatype) %>%
    summarize(content = paste(content, collapse = ";"), .groups = 'drop') %>%
    filter(ascatype == ascatype_filter) %>%
    ungroup()
  res <- df_subject_combined %>% select(c("uid", "content"))
  if (ascatype_filter == "extended"){
    colnames(res) <- c("uid", "Categories/ Classification")
  } else {
    colnames(res) <- c("uid", "Web of Science Categories")
  }
  return(res)
}
