function checkContent() {
  const targetId: string = getProperty_(testDocId);
  const targetDoc: GoogleAppsScript.Document.Document = getDocument_(targetId);
  const body: GoogleAppsScript.Document.Body = targetDoc.getBody();
  const paragraphs: GoogleAppsScript.Document.Paragraph[] =
    body.getParagraphs();
  paragraphs.forEach((paragraph, idx) => {
    const paragraphText: string = paragraph.getText();
    if (paragraphText !== checkTextArray[idx]) {
      if (
        paragraphText.replace('\\', '').replace('\\', '') !==
        checkTextArray[idx]
      ) {
        console.log(paragraphText);
        console.log(checkTextArray[idx]);
        throw new Error('Error: ' + paragraphText);
      }
    }
    const paragraphAttributes: string = paragraph.getHeading().toString();
    if (paragraphAttributes !== checkAttributeArray[idx]) {
      console.log(paragraphAttributes);
      console.log(checkAttributeArray[idx]);
      throw new Error('Error: ' + paragraphText);
    }
  });
  console.log('check ok.');
}
const checkAttributeArray: string[] = [
  'TITLE',
  'SUBTITLE',
  'HEADING1',
  'HEADING2',
  'HEADING3',
  'HEADING4',
  'HEADING5',
  'HEADING6',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'HEADING1',
  'HEADING2',
  'HEADING3',
  'HEADING4',
  'HEADING5',
  'HEADING6',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'HEADING1',
  'HEADING2',
  'HEADING3',
  'HEADING4',
  'HEADING5',
  'HEADING6',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'HEADING1',
  'HEADING2',
  'HEADING3',
  'HEADING4',
  'HEADING5',
  'HEADING6',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'HEADING1',
  'HEADING2',
  'HEADING3',
  'HEADING4',
  'HEADING5',
  'HEADING6',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'HEADING1',
  'HEADING2',
  'HEADING3',
  'HEADING4',
  'HEADING5',
  'HEADING6',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'HEADING1',
  'HEADING2',
  'HEADING3',
  'HEADING4',
  'HEADING5',
  'HEADING6',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
];

const checkTextArray: string[] = [
  'タイトル メイリオ14pts,中央揃え,段落前0pts,段落後10pts',
  'サブタイトル メイリオ10pts,中央揃え,段落前0pts,段落後0pts',
  '1. 正常系１',
  '1.1. Title',
  '1.1.1. Title',
  '1.1.1.1. Title',
  '1.1.1.1.1. Title',
  '1.1.1.1.1.1. Title',
  '箇条書き１',
  '箇条書き２',
  '箇条書き３',
  '通番１',
  '通番２',
  '通番３',
  '標準テキスト１',
  '標準テキスト２',
  '標準テキスト３',
  '',
  '表１',
  '表２',
  '表３',
  '表４',
  '表５',
  '表６',
  '2. 正常系２',
  '2.1. Title',
  '2.1.1. Title',
  '2.1.1.1. Title',
  '2.1.1.1.1. Title',
  '2.1.1.1.1.1. Title',
  '箇条書き１',
  '箇条書き２',
  '箇条書き３',
  '通番１',
  '通番２',
  '通番３',
  '標準テキスト１',
  '標準テキスト２',
  '標準テキスト３',
  '',
  '表１',
  '表２',
  '表３',
  '表４',
  '表５',
  '表６',
  '3. 最後のピリオドがないパターン',
  '3.1. Title',
  '3.1.1. Title',
  '3.1.1.1. Title',
  '3.1.1.1.1. Title',
  '3.1.1.1.1.1. Title',
  '箇条書き１',
  '箇条書き２',
  '箇条書き３',
  '通番１',
  '通番２',
  '通番３',
  '標準テキスト１',
  '標準テキスト２',
  '標準テキスト３',
  '',
  '表１',
  '表２',
  '表３',
  '表４',
  '表５',
  '表６',
  '4. 最後のピリオドが全角のパターン',
  '4.1. Title',
  '4.1.1. Title',
  '4.1.1.1. Title',
  '4.1.1.1.1. Title',
  '4.1.1.1.1.1. Title',
  '箇条書き１',
  '箇条書き２',
  '箇条書き３',
  '通番１',
  '通番２',
  '通番３',
  '標準テキスト１',
  '標準テキスト２',
  '標準テキスト３',
  '',
  '表１',
  '表２',
  '表３',
  '表４',
  '表５',
  '表６',
  '5. 章番号とTitleの間に半角スペースがないパターン',
  '5.1. Title',
  '5.1.1. Title',
  '5.1.1.1. Title',
  '5.1.1.1.1. Title',
  '5.1.1.1.1.1. Title',
  '箇条書き１',
  '箇条書き２',
  '箇条書き３',
  '通番１',
  '通番２',
  '通番３',
  '標準テキスト１',
  '標準テキスト２',
  '標準テキスト３',
  '',
  '表１',
  '表２',
  '表３',
  '表４',
  '表５',
  '表６',
  '6. 章番号とTitleの間が全角スペースのパターン',
  '6.1. Title',
  '6.1.1. Title',
  '6.1.1.1. Title',
  '6.1.1.1.1. Title',
  '6.1.1.1.1.1. Title',
  '箇条書き１',
  '箇条書き２',
  '箇条書き３',
  '通番１',
  '通番２',
  '通番３',
  '標準テキスト１',
  '標準テキスト２',
  '標準テキスト３',
  '',
  '表１',
  '表２',
  '表３',
  '表４',
  '表５',
  '表６',
  "7. test見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "7.1. test見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "7.1.1. test見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "7.1.1.1. test見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "7.1.1.1.1. test見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "7.1.1.1.1.1. test見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  '',
  'test27 表１',
  'test27 表２',
  'test27 表３',
  'test27 表４',
  'test27 表５',
  'test27 表６',
  '',
];
