function checkContent() {
  const targetId: string = getProperty_(testDocId);
  const targetDoc: GoogleAppsScript.Document.Document = getDocument_(targetId);
  const body: GoogleAppsScript.Document.Body = targetDoc.getBody();
  const paragraphs: GoogleAppsScript.Document.Paragraph[] =
    body.getParagraphs();
  paragraphs.forEach((paragraph, idx) => {
    const paragraphText: string = paragraph.getText();
    if (paragraphText !== checkTextArray[idx]) {
      if (
        paragraphText.replace('\\', '').replace('\\', '') !==
        checkTextArray[idx]
      ) {
        console.log(paragraphText);
        console.log(checkTextArray[idx]);
        throw new Error('Error: ' + paragraphText);
      }
    }
    const paragraphAttributes: string = paragraph.getHeading().toString();
    if (paragraphAttributes !== checkAttributeArray[idx]) {
      console.log(paragraphAttributes);
      console.log(checkAttributeArray[idx]);
      throw new Error('Error: ' + paragraphText);
    }
  });
  console.log('check ok.');
}
const checkAttributeArray: string[] = [
  'TITLE',
  'SUBTITLE',
  'HEADING1',
  'HEADING2',
  'HEADING3',
  'HEADING4',
  'HEADING5',
  'HEADING6',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'HEADING1',
  'HEADING2',
  'HEADING3',
  'HEADING4',
  'HEADING5',
  'HEADING6',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'HEADING1',
  'HEADING2',
  'HEADING3',
  'HEADING4',
  'HEADING5',
  'HEADING6',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'HEADING1',
  'HEADING2',
  'HEADING3',
  'HEADING4',
  'HEADING5',
  'HEADING6',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'HEADING1',
  'HEADING2',
  'HEADING3',
  'HEADING4',
  'HEADING5',
  'HEADING6',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'HEADING1',
  'HEADING2',
  'HEADING3',
  'HEADING4',
  'HEADING5',
  'HEADING6',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'HEADING1',
  'HEADING2',
  'HEADING3',
  'HEADING4',
  'HEADING5',
  'HEADING6',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'HEADING1',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'HEADING2',
  'NORMAL',
  'HEADING3',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'HEADING4',
  'NORMAL',
  'HEADING5',
  'NORMAL',
  'NORMAL',
  'HEADING6',
  'NORMAL',
  'HEADING3',
  'NORMAL',
  'NORMAL',
  'NORMAL',
  'HEADING2',
  'NORMAL',
  'HEADING3',
  'NORMAL',
];

const checkTextArray: string[] = [
  'タイトル メイリオ14pts,中央揃え,段落前0pts,段落後10pts',
  'サブタイトル メイリオ10pts,中央揃え,段落前0pts,段落後0pts',
  '1. 正常系１',
  '1.1. Title',
  '1.1.1. Title',
  '1.1.1.1. Title',
  '1.1.1.1.1. Title',
  '1.1.1.1.1.1. Title',
  '箇条書き１',
  '箇条書き２',
  '箇条書き３',
  '通番１',
  '通番２',
  '通番３',
  '標準テキスト１',
  '標準テキスト２',
  '標準テキスト３',
  '',
  '表１',
  '表２',
  '表３',
  '表４',
  '表５',
  '表６',
  '2. 正常系２',
  '2.1. Title',
  '2.1.1. Title',
  '2.1.1.1. Title',
  '2.1.1.1.1. Title',
  '2.1.1.1.1.1. Title',
  '箇条書き１',
  '箇条書き２',
  '箇条書き３',
  '通番１',
  '通番２',
  '通番３',
  '標準テキスト１',
  '標準テキスト２',
  '標準テキスト３',
  '',
  '表１',
  '表２',
  '表３',
  '表４',
  '表５',
  '表６',
  '3. 最後のピリオドがないパターン',
  '3.1. Title',
  '3.1.1. Title',
  '3.1.1.1. Title',
  '3.1.1.1.1. Title',
  '3.1.1.1.1.1. Title',
  '箇条書き１',
  '箇条書き２',
  '箇条書き３',
  '通番１',
  '通番２',
  '通番３',
  '標準テキスト１',
  '標準テキスト２',
  '標準テキスト３',
  '',
  '表１',
  '表２',
  '表３',
  '表４',
  '表５',
  '表６',
  '4. 最後のピリオドが全角のパターン',
  '4.1. Title',
  '4.1.1. Title',
  '4.1.1.1. Title',
  '4.1.1.1.1. Title',
  '4.1.1.1.1.1. Title',
  '箇条書き１',
  '箇条書き２',
  '箇条書き３',
  '通番１',
  '通番２',
  '通番３',
  '標準テキスト１',
  '標準テキスト２',
  '標準テキスト３',
  '',
  '表１',
  '表２',
  '表３',
  '表４',
  '表５',
  '表６',
  '5. 章番号とTitleの間に半角スペースがないパターン',
  '5.1. Title',
  '5.1.1. Title',
  '5.1.1.1. Title',
  '5.1.1.1.1. Title',
  '5.1.1.1.1.1. Title',
  '箇条書き１',
  '箇条書き２',
  '箇条書き３',
  '通番１',
  '通番２',
  '通番３',
  '標準テキスト１',
  '標準テキスト２',
  '標準テキスト３',
  '',
  '表１',
  '表２',
  '表３',
  '表４',
  '表５',
  '表６',
  '6. 章番号とTitleの間が全角スペースのパターン',
  '6.1. Title',
  '6.1.1. Title',
  '6.1.1.1. Title',
  '6.1.1.1.1. Title',
  '6.1.1.1.1.1. Title',
  '箇条書き１',
  '箇条書き２',
  '箇条書き３',
  '通番１',
  '通番２',
  '通番３',
  '標準テキスト１',
  '標準テキスト２',
  '標準テキスト３',
  '',
  '表１',
  '表２',
  '表３',
  '表４',
  '表５',
  '表６',
  "7. test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "7.1. test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "7.1.1. test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "7.1.1.1. test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "7.1.1.1.1. test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "7.1.1.1.1.1. test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  "test27 見出しの文字列が'^.+[\d]+[\s|S].*$'の形式の時半角空白の前の数字が欠落する, この例ではtest27->testになる",
  '',
  'test27 表１',
  'test27 表２',
  'test27 表３',
  'test27 表４',
  'test27 表５',
  'test27 表６',
  '8. 見出し1. プロジェクト概要 Ver.1.0',
  'プロジェクト「Alpha 1.0」の概要を説明します。2023年に開始し、以下のステップで進めています：',
  '企画（1か月）',
  '開発（2.5か月）',
  'テスト（0.5か月）',
  '8.1. 見出し2 - 詳細設計 2．0',
  'このセクションでは、プロジェクトの設計について説明します。設計段階では「バージョン2.1」を想定した変更を含みます。',
  '8.1.1. 見出し3.1.1. - データフロー設計 Ver．3. 1',
  'データフローの設計について述べます。たとえば、次の3つの要素を含みます：',
  '入力データの形式（例：CSV, JSON）',
  'データサイズ（最大5GB）',
  '処理速度（目標：0.2秒以下）',
  '8.1.1.1. セキュリティ要件 Ver 4．0 システムの安全性を確保するための要件を定義します。不正アクセスやデータ漏洩を防ぐ対策を講じます。',
  'セキュリティ要件には、暗号化、認証プロセスの強化、ログ監視が含まれます。',
  '8.1.1.1.1. アクセス制御 5.',
  'ユーザーがアクセス可能な範囲を設定し、権限管理を実施します。管理者と一般ユーザーで権限を区別します。',
  '許可されたIPアドレスのみ接続可能とし、不正アクセスをブロックする仕組みを導入します。',
  '8.1.1.1.1.1. ログ管理 Ver．6.0',
  'システムログの保存と管理を行います。これにより、障害発生時の原因特定が容易になります。ログは7日間保存され、1日ごとに自動アーカイブされます。',
  '8.1.2. header3. セキュリティ要件 Ver 4．0',
  'セキュリティ面での要件を列挙します。2024年までに次の目標を達成します：',
  '暗号化方式をAES-256にアップデート',
  '認証プロセスを2段階に強化',
  '8.2. 2- 見出し2 - アクセス制御 5.',
  'アクセス制御の詳細について説明します。許可されたIPアドレス範囲は「192.168.0.0/24」に限定されます。',
  '8.2.1. .3 - ログ管理 Ver．6. 0',
  'ログの管理方法を記載します。ログは「1.1GB」未満で圧縮され、7日間保持されます。',
];
